# Project Name
TARGET = Main

# Sources
CPP_SOURCES = Main.cpp

# TODO: This should probably have a way to add libraries like ulibsd from here.

# Library Locations
LIBDAISY_DIR = ../libDaisy
DAISYSP_DIR = ../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile


